title: Home
email: 
description: "marcus8448's home."
baseurl: "/"
url: "https://marcus8448.github.io/"
twitter_username: marcus8448
github_username: marcus8448

sass:
  style: compressed

theme:
plugins:
  - jekyll-feed

projects:
  - url: galacticraft
    name: Galacticraft
    type: Minecraft Mod
    language: Java
  - url: gamemode_overhaul
    name: GamemodeOverhaul
    type: Minecraft Mod
    language: Java
  - url: project-ile
    name: Project-ILE
    type: Minecraft Mod
    language: Java

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .idea/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
